extends SceneTree

const PREFAB_PATH: String = "res://scenes/prefabs/environment/d01_sports_pavilion_01.tscn"
const MODEL_PATH: String = (
	"res://art/models/environment/d01_sports_pavilion_01/d01_sports_pavilion_01.glb"
)
const DEFAULT_OUTPUT: String = "C:/tmp/ft/assets/d01_sports_pavilion_01/prefab-check.json"
const EXPECTED_BOUNDS: AABB = (
	AABB(Vector3(-22.960832, 0, -8.568231), Vector3(45.921664, 6.555, 17.149255))
)
const TOLERANCE_M: float = 0.001
const WORLD_LAYER: int = 1
const EDITOR_STARTUP_FRAMES: int = 10
const ACTOR_RADIUS_M: float = 0.35
const ACTOR_HEIGHT_M: float = 1.8
const EAST_FACADE_PLANE_NORMAL: Vector2 = Vector2(.422_618, .906_308)
const EAST_FACADE_PLANE_DISTANCE_M: float = 4.124628
const MOTION_TICKS: int = 144

var _failures: Array[String] = []
var _result: Dictionary = {}


## Defer until the headless scene tree can register physics objects.
func _initialize() -> void:
	_run.call_deferred()


## Record a failed assertion and return a nonzero final exit rather than silently continuing.
func _expect(condition: bool, message: String) -> void:
	if not condition:
		_failures.append(message)
		push_error(message)


## Normalize only this owned prefab and prove that a second pack/save is byte-stable.
func _roundtrip() -> void:
	var original: PackedScene = load(PREFAB_PATH) as PackedScene
	_expect(original != null, "Prefab must load before normalization")
	if original == null:
		return

	var instance: Node = original.instantiate()
	var packed: PackedScene = PackedScene.new()
	_expect(packed.pack(instance) == OK, "Prefab pack failed")
	_expect(ResourceSaver.save(packed, PREFAB_PATH) == OK, "Prefab save failed")
	instance.free()
	var first: String = FileAccess.get_sha256(PREFAB_PATH)
	var reloaded: PackedScene = ResourceLoader.load(
		PREFAB_PATH, "PackedScene", ResourceLoader.CACHE_MODE_IGNORE
	) as PackedScene
	instance = reloaded.instantiate()
	packed = PackedScene.new()
	_expect(packed.pack(instance) == OK, "Reloaded prefab pack failed")
	_expect(ResourceSaver.save(packed, PREFAB_PATH) == OK, "Reloaded prefab save failed")
	instance.free()
	_result["save_reload_byte_stable"] = first == FileAccess.get_sha256(PREFAB_PATH)
	_expect(_result["save_reload_byte_stable"], "Second prefab save changed bytes")


## Inspect the linked import, its actual bounds/materials, and authored collision shapes.
func _inspect(instance: Node3D) -> void:
	var model: Node3D = instance.get_node("Visuals/Model") as Node3D
	_expect(model.scene_file_path == MODEL_PATH, "Model lost linked GLB ancestry")
	_expect(model.transform == Transform3D.IDENTITY, "Model transform is not identity")
	var meshes: Array[Node] = model.find_children("*", "MeshInstance3D", true, false)
	_expect(meshes.size() == 1, "Expected one imported mesh")
	var mesh_instance: MeshInstance3D = meshes[0] as MeshInstance3D
	var bounds: AABB = mesh_instance.global_transform * mesh_instance.get_aabb()
	_expect(bounds.position.distance_to(EXPECTED_BOUNDS.position) < TOLERANCE_M, "Bounds min")
	_expect(bounds.size.distance_to(EXPECTED_BOUNDS.size) < TOLERANCE_M, "Bounds size")
	_expect(mesh_instance.mesh.resource_path.begins_with(MODEL_PATH), "Mesh is not imported")
	_expect(mesh_instance.mesh.get_surface_count() == 7, "Expected seven material surfaces")
	var materials: Array[String] = []
	for index: int in range(mesh_instance.mesh.get_surface_count()):
		var material: BaseMaterial3D = (
			mesh_instance.mesh.surface_get_material(index) as BaseMaterial3D
		)
		_expect(material != null, "Missing imported material")
		_expect(material.transparency == BaseMaterial3D.TRANSPARENCY_DISABLED, "Opaque material")
		_expect(material.cull_mode == BaseMaterial3D.CULL_BACK, "Back-culling material")
		materials.append(material.resource_name)

	var body: StaticBody3D = instance.get_node("Collision/Body") as StaticBody3D
	_expect(body.collision_layer == WORLD_LAYER and body.collision_mask == 0, "Static world layers")
	_expect(body.get_child_count() == 2, "Expected two service-wedge colliders")
	_result["aabb_min"] = [bounds.position.x, bounds.position.y, bounds.position.z]
	_result["aabb_size"] = [bounds.size.x, bounds.size.y, bounds.size.z]
	_result["materials"] = materials
	_result["mesh_count"] = meshes.size()
	_result["collision_shape_count"] = body.get_child_count()
	_result["linked_model_identity"] = model.transform == Transform3D.IDENTITY
	var prefab_uid: int = ResourceLoader.get_resource_uid(PREFAB_PATH)
	var model_uid: int = ResourceLoader.get_resource_uid(MODEL_PATH)
	_expect(prefab_uid != ResourceUID.INVALID_ID, "Prefab UID must be generated by editor save")
	_expect(model_uid != ResourceUID.INVALID_ID, "Model UID must resolve from import sidecar")
	_result["prefab_uid"] = ResourceUID.id_to_text(prefab_uid)
	_result["model_uid"] = ResourceUID.id_to_text(model_uid)


## Check literal service-wedge footprints, shared seam, open apron and overhead exclusions.
func _physics_checks(instance: Node3D) -> void:
	var space: PhysicsDirectSpaceState3D = instance.get_world_3d().direct_space_state
	var sphere: SphereShape3D = SphereShape3D.new()
	sphere.radius = 0.03
	var cases: Array[Dictionary] = [
		{ "name": "centre_joint_solid", "point": Vector3(0, 1, 5.5), "solid": true },
		{ "name": "west_wall_solid", "point": Vector3(-10, 1, 1), "solid": true },
		{ "name": "east_wall_solid", "point": Vector3(10, 1, 1), "solid": true },
		{ "name": "west_front_corner", "point": Vector3(-18.35, 1, -3.9), "solid": true },
		{ "name": "east_front_corner", "point": Vector3(18.35, 1, -3.9), "solid": true },
		{ "name": "west_rear_corner", "point": Vector3(-19.75, 1, -2.7), "solid": true },
		{ "name": "east_rear_corner", "point": Vector3(19.75, 1, -2.7), "solid": true },
		{ "name": "front_seam_clear", "point": Vector3(0, 1, 4.4), "solid": false },
		{ "name": "rear_seam_clear", "point": Vector3(0, 1, 6.7), "solid": false },
		{ "name": "apron_centre_clear", "point": Vector3(0, 1, 0), "solid": false },
		{ "name": "west_apron_clear", "point": Vector3(-10, 1, -2), "solid": false },
		{ "name": "east_apron_clear", "point": Vector3(10, 1, -2), "solid": false },
		{ "name": "west_end_clear", "point": Vector3(-20.2, 1, -3), "solid": false },
		{ "name": "east_end_clear", "point": Vector3(20.2, 1, -3), "solid": false },
		{ "name": "roof_visual_only", "point": Vector3(0, 6, 5.5), "solid": false },
	]
	var observations: Array[Dictionary] = []
	var query: PhysicsShapeQueryParameters3D = PhysicsShapeQueryParameters3D.new()
	query.shape = sphere
	query.collision_mask = WORLD_LAYER
	for test: Dictionary in cases:
		query.transform.origin = test["point"]
		var solid: bool = not space.intersect_shape(query).is_empty()
		_expect(solid == test["solid"], "Shape query failed: " + str(test["name"]))
		observations.append({ "case": test["name"], "solid": solid })

	_result["physics_shape_queries"] = observations
	_face_ray_checks(space)
	_check_collision_shapes(instance)


## Inspect the bounded dimension-authored shape count and identity transforms.
func _check_collision_shapes(instance: Node3D) -> void:
	var body: StaticBody3D = instance.get_node("Collision/Body") as StaticBody3D
	for child: Node in body.get_children():
		var collider: CollisionShape3D = child as CollisionShape3D
		_expect(collider.transform == Transform3D.IDENTITY, "Wedge collision transform")
		var shape: ConvexPolygonShape3D = collider.shape as ConvexPolygonShape3D
		_expect(shape != null and shape.points.size() == 8, "Eight-point dimension-authored wedge")


## Compare literal face datums at two heights, rejecting gaps or a filled concave hull.
func _face_ray_checks(space: PhysicsDirectSpaceState3D) -> void:
	var datums: Array[Vector3] = [
		Vector3(0, 4.551024, 6.551024),
		Vector3(5, 2.219486, 4.219486),
		Vector3(10, -.112_053, 1.887947),
		Vector3(17, -3.376207, -1.376207),
	]
	var hits: Array[Dictionary] = []
	for datum: Vector3 in datums:
		for side: float in [-1.0, 1.0]:
			for height: float in [.2, 4.8]:
				hits.append(_face_ray(space, Vector3(datum.x * side, height, datum.y), true))
				hits.append(_face_ray(space, Vector3(datum.x * side, height, datum.z), false))

	_result["footprint_face_ray_hits"] = hits


## Check one face ray against an independent expected contact position.
func _face_ray(space: PhysicsDirectSpaceState3D, expected: Vector3, front: bool) -> Dictionary:
	var start: Vector3 = Vector3(expected.x, expected.y, -12 if front else 12)
	var end: Vector3 = Vector3(expected.x, expected.y, 12 if front else -12)
	var ray: PhysicsRayQueryParameters3D = PhysicsRayQueryParameters3D.create(
		start,
		end,
		WORLD_LAYER,
	)
	var hit: Dictionary = space.intersect_ray(ray)
	_expect(not hit.is_empty(), "A service-wedge face ray missed")
	if hit.is_empty():
		return {}

	var point: Vector3 = hit["position"]
	_expect(point.distance_to(expected) < TOLERANCE_M, "Wedge face mismatch")
	return { "x": point.x, "y": point.y, "z": point.z }


## Exercise the production movement API against the saved prefab, not a copied movement formula.
func _move_probe(start: Vector3, move: Vector2, mode: ActorMotion.StepMode) -> Vector3:
	var actor: ActorMotion = ActorMotion.new()
	actor.collision_layer = 0
	actor.collision_mask = WORLD_LAYER
	var capsule: CapsuleShape3D = CapsuleShape3D.new()
	capsule.radius = ACTOR_RADIUS_M
	capsule.height = ACTOR_HEIGHT_M
	var collider: CollisionShape3D = CollisionShape3D.new()
	collider.shape = capsule
	collider.position.y = ACTOR_HEIGHT_M / 2.0
	actor.add_child(collider)
	root.add_child(actor)
	actor.position = start
	await physics_frame
	var command: FootCommand = FootCommand.new(1, 0, move, 0.0, false, false)
	var fixed_delta: float = 1.0 / float(Engine.physics_ticks_per_second)
	# Real fixed frames are required: this intentionally serializes the physics probe.
	for tick: int in range(MOTION_TICKS):
		await physics_frame  # gdstyle:ignore=quality/await-in-loop
		_expect(actor.step(command, fixed_delta, mode), "Production motion rejected test intent")

	var end: Vector3 = actor.global_position
	actor.queue_free()
	await physics_frame
	return end


## Exercise the seam stop, slanted facade stop and unblocked field-side passage in both modes.
func _movement_checks() -> void:
	# Test-only invisible ground; production placement supplies the flat ground datum.
	var ground: StaticBody3D = StaticBody3D.new()
	ground.collision_layer = WORLD_LAYER
	ground.collision_mask = 0
	var shape: BoxShape3D = BoxShape3D.new()
	shape.size = Vector3(100, .5, 100)
	var collider: CollisionShape3D = CollisionShape3D.new()
	collider.shape = shape
	collider.position.y = -.25
	ground.add_child(collider)
	root.add_child(ground)
	await physics_frame
	var observations: Array[Dictionary] = []
	for mode: ActorMotion.StepMode in [ActorMotion.StepMode.AUTHORITY, ActorMotion.StepMode.REPLAY]:
		var seam: Vector3 = await _move_probe(  # gdstyle:ignore=quality/await-in-loop
			Vector3(0, 0, 0), Vector2(0, 1), mode
		)
		_expect(seam.z > 4.1 and seam.z < 4.3, "Actor must stop at the closed central seam")
		_expect(absf(seam.y) < .03, "No step or raised deck at ground datum")
		var bypass: Vector3 = await _move_probe(  # gdstyle:ignore=quality/await-in-loop
			Vector3(-6, 0, -6), Vector2(1, 0), mode
		)
		_expect(bypass.x > 5.9 and bypass.x < 6.1, "Field-side passage must allow 12 m traversal")
		var wall: Vector3 = await _move_probe(  # gdstyle:ignore=quality/await-in-loop
			Vector3(0, 0, 0), Vector2(1, 0), mode
		)
		# Distance from the literal 25-degree facade plane, not a fixed-axis stop:
		# move_and_slide may continue along the wall while preserving capsule clearance.
		var clearance: float = EAST_FACADE_PLANE_DISTANCE_M
		clearance -= EAST_FACADE_PLANE_NORMAL.dot(Vector2(wall.x, wall.z))
		_expect(clearance > .34, "Slanted facade must preserve actor radius outside the wall")
		_expect(wall.x < 12 and wall.z < -.5, "Slanted facade must deflect toward open field")
		observations.append({
			"mode": mode,
			"seam_end": [seam.x, seam.y, seam.z],
			"bypass_end": [bypass.x, bypass.y, bypass.z],
			"wall_end": [wall.x, wall.y, wall.z],
		})

	_expect(observations[0]["seam_end"] == observations[1]["seam_end"], "Seam replay mismatch")
	_expect(
		observations[0]["bypass_end"] == observations[1]["bypass_end"], "Bypass replay mismatch"
	)
	_expect(observations[0]["wall_end"] == observations[1]["wall_end"], "Wall replay mismatch")
	_result["production_actor_motion"] = observations
	ground.queue_free()
	await physics_frame


## Run bounded resource and physics checks without starting the game or touching live editors.
func _run() -> void:
	if Engine.is_editor_hint():
		for frame: int in range(EDITOR_STARTUP_FRAMES):
			await process_frame  # gdstyle:ignore=quality/await-in-loop
		while EditorInterface.get_resource_filesystem().is_scanning():
			await process_frame  # gdstyle:ignore=quality/await-in-loop

	var arguments: PackedStringArray = OS.get_cmdline_user_args()
	if arguments.has("--normalize"):
		# Runtime ResourceSaver strips scene/dependency UIDs on this pin.
		_expect(Engine.is_editor_hint(), "UID-preserving normalization requires --editor")
		if Engine.is_editor_hint():
			_roundtrip()

	var packed: PackedScene = ResourceLoader.load(
		PREFAB_PATH, "PackedScene", ResourceLoader.CACHE_MODE_IGNORE
	) as PackedScene
	_expect(packed != null, "Prefab dependencies must resolve")
	if packed != null:
		var instance: Node3D = packed.instantiate() as Node3D
		root.add_child(instance)
		_inspect(instance)
		if not Engine.is_editor_hint():
			await physics_frame
			await physics_frame
			_physics_checks(instance)
			await _movement_checks()
		instance.queue_free()
		await process_frame

	_result["engine"] = Engine.get_version_info()["string"]
	_result["failures"] = _failures
	_result["ok"] = _failures.is_empty()
	var output: String = DEFAULT_OUTPUT
	var output_index: int = arguments.find("--output")
	if output_index >= 0 and output_index + 1 < arguments.size():
		output = arguments[output_index + 1]

	var file: FileAccess = FileAccess.open(output, FileAccess.WRITE)
	file.store_string(JSON.stringify(_result, "\t") + "\n")
	file.close()
	print(JSON.stringify(_result))
	quit(0 if _failures.is_empty() else 1)
