#!/usr/bin/env python3
"""Embed the saved neutral street SVG and owner-drawn district boundaries for file:// use."""
import importlib.util
import hashlib
import json
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT.parent / '02-city-without-zone-colours.svg'
spec = importlib.util.spec_from_file_location(
    'macro', ROOT.parent.parent / 'stage-02-city-structure/draw_maps.py')
macro = importlib.util.module_from_spec(spec)
spec.loader.exec_module(macro)
ET.register_namespace('', 'http://www.w3.org/2000/svg')
svg = ET.parse(SOURCE).getroot()
map_group = next(node for node in svg if node.get('transform') == 'translate(30 225) scale(1.5)')
# Drop the old fixed district badges; the editor labels the current polygons.
for node in list(map_group):
    if (node.tag.endswith('circle') and node.get('fill') == '#102332') or (
            node.tag.endswith('text') and (node.text or '') in {str(i) for i in range(1, 10)}):
        map_group.remove(node)
background = ''.join(ET.tostring(node, encoding='unicode') for node in map_group)
boundaries_text = (ROOT / 'brackett-districts.json').read_text()
boundaries = json.loads(boundaries_text)


water = next(node.get('d') for node in map_group.iter()
             if node.tag.endswith('path') and node.get('fill') == '#102C40')
data = dict(
    background=background, land=macro.polygon(macro.LAND), water=water,
    revision=hashlib.sha256(boundaries_text.encode()).hexdigest()[:12],
    districts=boundaries['districts'])
(ROOT / 'map-data.js').write_text(
    '// Generated by generate_map.py from the saved neutral map; do not edit by hand.\n'
    + 'window.DISTRICT_MAP = ' + json.dumps(data, separators=(',', ':')) + ';\n')
print('Embedded neutral map and nine owner-drawn districts.')
