from pathlib import Path
import json
r=Path('/home/regner/.paseo/worktrees/0u71f39f/s06-provisional-turn-seam')
s=(r/'tests/fixtures/s06/city.gd').read_text()
s=s.replace('const ENDPOINT_TOLERANCE_M:', 'const MAX_CONTROLS: int = 16\nconst MAX_LINK_LENGTH_M: float = 128.0\nconst BAKE_INTERVAL_M: float = 0.25\nconst ENDPOINT_TOLERANCE_M:')
s=s.replace('return "OK"\n\n\n## Computes', 'return "OK" if _roads_match(records.links) else "CONTENT_INVALID"\n\n\n## Computes',1)
s=s.replace('node is S06Anchor or node is S06Link:', 'node is S06Anchor or node is S06Link or node is S06Sector:')
s=s.replace('link.curve == null or link.curve.point_count < 2:', 'not _curve_valid(link):')
s=s.replace('if node is S06Anchor:\n\t\trows.append', 'if node is S06Anchor or node is S06Sector:\n\t\trows.append')
s+='''\n\n## Bounds curve allocation from authored control polygons before engine baking.\nfunc _curve_valid(link: S06Link) -> bool:\n\tif link.curve == null or link.curve.point_count < 2:\n\t\treturn false\n\tif link.curve.point_count > MAX_CONTROLS or link.curve.bake_interval != BAKE_INTERVAL_M:\n\t\treturn false\n\n\tvar length: float = 0.0\n\tfor index: int in link.curve.point_count:\n\t\tvar point: Vector3 = link.curve.get_point_position(index)\n\t\tvar incoming: Vector3 = link.curve.get_point_in(index)\n\t\tvar outgoing: Vector3 = link.curve.get_point_out(index)\n\t\tif not point.is_finite() or not incoming.is_finite() or not outgoing.is_finite():\n\t\t\treturn false\n\t\tif not link.to_global(point).is_finite():\n\t\t\treturn false\n\t\tif index > 0:\n\t\t\tvar previous: Vector3 = link.curve.get_point_position(index - 1)\n\t\t\tvar previous_out: Vector3 = link.curve.get_point_out(index - 1)\n\t\t\tlength += previous_out.length() + incoming.length() + (\n\t\t\t\tprevious + previous_out).distance_to(point + incoming)\n\n\treturn is_finite(length) and length <= MAX_LINK_LENGTH_M\n\n\n## Detects missing, duplicated or manually corrupted derived roads as well as stale placement.\nfunc _roads_match(links: Array[S06Link]) -> bool:\n\tvar expected: Dictionary = {}\n\tfor link: S06Link in links:\n\t\tif link.kind == "ROAD":\n\t\t\texpected[str(link.world_id)] = link\n\tif derived.roads.size() != expected.size():\n\t\treturn false\n\n\tvar seen: Dictionary = {}\n\tvar samples: int = 0\n\tfor road: Dictionary in derived.roads:\n\t\tif not road.has_all(["id", "width_m", "points"]) or not expected.has(road.id):\n\t\t\treturn false\n\t\tif seen.has(road.id) or typeof(road.points) != TYPE_PACKED_VECTOR3_ARRAY:\n\t\t\treturn false\n\n\t\tseen[road.id] = true\n\t\tvar link: S06Link = expected[road.id]\n\t\tvar points: PackedVector3Array = _points(link, false)\n\t\tif road.width_m != link.width_m or road.points != points:\n\t\t\treturn false\n\n\t\tsamples += points.size()\n\t\tif samples > MAX_SAMPLES:\n\t\t\treturn false\n\n\treturn true\n'''
h=(r/'tools/s06/editor_probe.gd').read_text().replace('city.derived = result','city.derived = load(path)')
p=(r/'tests/fixtures/s06/proof.gd').read_text()
p=p.replace('\t_saved_counterexamples(fixture, city)', '\t_passive_and_map_checks(fixture, city)\n\t_saved_counterexamples(fixture, city)')
p+='''\n\n## Checks pre-tree passive bodies, actual minimap projection and corrupted bake rejection.\nfunc _passive_and_map_checks(fixture: S06Fixture, city: S06City) -> void:\n\tvar west: S04Kinematic = fixture.get_node("CarWest")\n\tvar east: S04Kinematic = fixture.get_node("CarEast")\n\tvar person: S02ActorMotion = fixture.get_node("Person")\n\t_expect(not west.simulation_enabled and not east.simulation_enabled and\n\t\twest.collision_layer == 0 and east.collision_mask == 0 and\n\t\tperson.collision_layer == 0, "bodies passive before command admission")\n\tfixture.authoritative = false\n\t_expect(fixture.start_route("foot") == "NOT_OWNER", "passive fixture refuses body commands")\n\tfixture.authoritative = true\n\tvar minimap: S06Minimap = fixture.get_node("Ui/Minimap")\n\t_expect(minimap.project_point(Vector3(-24, 0, 0)).distance_to(Vector2(8, 80)) < 0.1,\n\t\t"actual minimap west endpoint projection")\n\t_expect(minimap.project_point(Vector3(24, 0, 0)).distance_to(Vector2(152, 80)) < 0.1,\n\t\t"actual minimap east endpoint projection")\n\t_expect(minimap.project_point(Vector3.ZERO).distance_to(Vector2(80, 80)) < 0.1,\n\t\t"actual minimap shared seam projection")\n\tvar original: S06Bake = city.derived\n\tcity.derived = original.duplicate(true)\n\tvar moved: PackedVector3Array = city.derived.roads[0].points\n\tmoved[0].x += 1.0\n\tcity.derived.roads[0].points = moved\n\t_expect(city.validate_content() == "CONTENT_INVALID", "corrupted derived road refused")\n\t_expect(minimap.bind_city(city) == "CONTENT_INVALID" and not minimap.content_valid,\n\t\t"invalid bake clears minimap drawing")\n\tcity.derived = original\n\t_expect(minimap.bind_city(city) == "OK", "restored minimap admitted")\n'''
print(json.dumps({'city.gd':s,'proof.gd':p,'editor_probe.gd':h}))
