extends SceneTree

const PREFAB_PATH: String = "res://scenes/prefabs/environment/d07_sign_island_01.tscn"
const MODEL_PATH: String = (
	"res://art/models/environment/d07_sign_island_01/d07_sign_island_01.glb"
)
const DEFAULT_OUTPUT: String = "C:/tmp/ft/assets/d07_sign_island_01/prefab-check.json"
const EXPECTED_BOUNDS: AABB = AABB(Vector3(-3, 0, -3), Vector3(6, 0.28, 6))
const TOLERANCE_M: float = 0.001
const CONTACT_TOLERANCE_M: float = 0.005
const WORLD_LAYER: int = 1
const EDITOR_STARTUP_SECONDS: float = 3.0
const CHECK_DEADLINE_SECONDS: float = 60.0

var _failures: Array[String] = []
var _result: Dictionary = {}


## Defer until the headless scene tree can register physics objects.
func _initialize() -> void:
	create_timer(CHECK_DEADLINE_SECONDS).timeout.connect(_deadline)
	_run.call_deferred()


## Fail closed when an asynchronous engine operation does not complete.
func _deadline() -> void:
	push_error("Sign-island prefab check did not finish within 60 seconds")
	quit(1)


## Record a failed assertion and return a nonzero final exit rather than silently continuing.
func _expect(condition: bool, message: String) -> void:
	if not condition:
		_failures.append(message)
		push_error(message)


## Normalize only this owned prefab and prove that a second pack/save is byte-stable.
func _roundtrip() -> void:
	var original: PackedScene = load(PREFAB_PATH) as PackedScene
	_expect(original != null, "Prefab must load before normalization")
	if original == null:
		return

	var instance: Node = original.instantiate()
	var packed: PackedScene = PackedScene.new()
	_expect(packed.pack(instance) == OK, "Prefab pack failed")
	_expect(ResourceSaver.save(packed, PREFAB_PATH) == OK, "Prefab save failed")
	instance.free()
	var first: String = FileAccess.get_sha256(PREFAB_PATH)
	_expect(FileAccess.get_file_as_string(PREFAB_PATH).contains("uid=\"uid://"), "Saved UID")
	var reloaded: PackedScene = ResourceLoader.load(
		PREFAB_PATH, "PackedScene", ResourceLoader.CACHE_MODE_IGNORE
	) as PackedScene
	instance = reloaded.instantiate()
	packed = PackedScene.new()
	_expect(packed.pack(instance) == OK, "Reloaded prefab pack failed")
	_expect(ResourceSaver.save(packed, PREFAB_PATH) == OK, "Reloaded prefab save failed")
	instance.free()
	_result["save_reload_byte_stable"] = first == FileAccess.get_sha256(PREFAB_PATH)
	_expect(_result["save_reload_byte_stable"], "Second prefab save changed bytes")
	_result["prefab_sha256"] = FileAccess.get_sha256(PREFAB_PATH)


## Inspect the linked import, its actual bounds/materials, and authored collision shapes.
func _inspect(instance: Node3D) -> void:
	var model: Node3D = instance.get_node("Visuals/Model") as Node3D
	_expect(model.scene_file_path == MODEL_PATH, "Model lost linked GLB ancestry")
	_expect(model.transform == Transform3D.IDENTITY, "Model transform is not identity")
	var meshes: Array[Node] = model.find_children("*", "MeshInstance3D", true, false)
	_expect(meshes.size() == 1, "Expected one imported mesh")
	var mesh_instance: MeshInstance3D = meshes[0] as MeshInstance3D
	var bounds: AABB = mesh_instance.global_transform * mesh_instance.get_aabb()
	_expect(bounds.position.distance_to(EXPECTED_BOUNDS.position) < TOLERANCE_M, "Bounds min")
	_expect(bounds.size.distance_to(EXPECTED_BOUNDS.size) < TOLERANCE_M, "Bounds size")
	_expect(mesh_instance.mesh.resource_path.begins_with(MODEL_PATH), "Mesh is not imported")
	_expect(mesh_instance.mesh.get_surface_count() == 3, "Expected three material surfaces")
	var materials: Array[String] = []
	for index: int in range(mesh_instance.mesh.get_surface_count()):
		var material: BaseMaterial3D = (
			mesh_instance.mesh.surface_get_material(index) as BaseMaterial3D
		)
		_expect(material != null, "Missing imported material")
		_expect(material.transparency == BaseMaterial3D.TRANSPARENCY_DISABLED, "Opaque material")
		_expect(material.cull_mode == BaseMaterial3D.CULL_BACK, "Back-culling material")
		materials.append(material.resource_name)

	var body: StaticBody3D = instance.get_node("Collision/Body") as StaticBody3D
	_expect(body.collision_layer == WORLD_LAYER and body.collision_mask == 0, "Static world layers")
	_expect(body.get_child_count() == 1, "Expected one continuous cylinder")
	_inspect_collision(body)

	_result["aabb_min"] = [bounds.position.x, bounds.position.y, bounds.position.z]
	_result["aabb_size"] = [bounds.size.x, bounds.size.y, bounds.size.z]
	_result["materials"] = materials
	_result["mesh_count"] = meshes.size()
	_result["collision_shape_count"] = body.get_child_count()
	_result["linked_model_identity"] = model.transform == Transform3D.IDENTITY
	var prefab_uid: int = ResourceLoader.get_resource_uid(PREFAB_PATH)
	var model_uid: int = ResourceLoader.get_resource_uid(MODEL_PATH)
	_expect(prefab_uid != ResourceUID.INVALID_ID, "Prefab UID must be generated by editor save")
	_expect(model_uid != ResourceUID.INVALID_ID, "Model UID must resolve from import sidecar")
	_result["prefab_uid"] = ResourceUID.id_to_text(prefab_uid)
	_result["model_uid"] = ResourceUID.id_to_text(model_uid)


## Verify the single continuous walk/blocking envelope independently of visual detail.
func _inspect_collision(body: StaticBody3D) -> void:
	var shape_node: CollisionShape3D = body.get_node("Base") as CollisionShape3D
	var cylinder: CylinderShape3D = shape_node.shape as CylinderShape3D
	_expect(cylinder != null, "Base collider must remain a cylinder")
	_expect(is_equal_approx(cylinder.radius, 3.0), "Cylinder radius must be 3 m")
	_expect(is_equal_approx(cylinder.height, 0.28), "Cylinder height must be 0.28 m")
	_expect(shape_node.position.is_equal_approx(Vector3(0, 0.14, 0)), "Cylinder centre datum")
	_expect(not shape_node.disabled, "Collider must be enabled")


## Probe literal interior/exterior positions and a continuous top through engine queries.
func _physics_checks(instance: Node3D) -> void:
	var space: PhysicsDirectSpaceState3D = instance.get_world_3d().direct_space_state
	var sphere: SphereShape3D = SphereShape3D.new()
	sphere.radius = 0.05
	var cases: Array[Dictionary] = [
		{ "name": "centre_solid", "point": Vector3(0, 0.14, 0), "solid": true },
		{ "name": "north_rim", "point": Vector3(0, 0.14, -2.97), "solid": true },
		{ "name": "south_rim", "point": Vector3(0, 0.14, 2.97), "solid": true },
		{ "name": "east_rim", "point": Vector3(2.97, 0.14, 0), "solid": true },
		{ "name": "west_rim", "point": Vector3(-2.97, 0.14, 0), "solid": true },
		{ "name": "outside_north", "point": Vector3(0, 0.14, -3.2), "solid": false },
		{ "name": "outside_east", "point": Vector3(3.2, 0.14, 0), "solid": false },
		{ "name": "outside_diagonal", "point": Vector3(2.3, 0.14, 2.3), "solid": false },
		{ "name": "over_deck", "point": Vector3(0, 0.4, 0), "solid": false },
		{ "name": "below_base", "point": Vector3(0, -0.1, 0), "solid": false },
	]
	var observations: Array[Dictionary] = []
	var query: PhysicsShapeQueryParameters3D = PhysicsShapeQueryParameters3D.new()
	query.shape = sphere
	query.collision_mask = WORLD_LAYER
	for test: Dictionary in cases:
		query.transform.origin = test["point"]
		var solid: bool = not space.intersect_shape(query).is_empty()
		_expect(solid == test["solid"], "Shape query failed: " + str(test["name"]))
		observations.append({ "case": test["name"], "solid": solid })

	_result["physics_shape_queries"] = observations
	var ray_heights: Array[float] = []
	for point: Vector3 in [Vector3.ZERO, Vector3(2, 0, 2), Vector3(-2, 0, -2)]:
		var ray: PhysicsRayQueryParameters3D = PhysicsRayQueryParameters3D.create(
			point + Vector3.UP, point + Vector3.DOWN, WORLD_LAYER
		)
		var hit: Dictionary = space.intersect_ray(ray)
		_expect(not hit.is_empty(), "Top must be continuous")
		if not hit.is_empty():
			var position: Vector3 = hit["position"]
			_expect(absf(position.y - 0.28) < TOLERANCE_M, "Top datum must be 0.28 m")
			ray_heights.append(position.y)

	_result["top_ray_heights_m"] = ray_heights


## Sweep a real actor-size capsule at the edge, beside it, and down onto its deck.
func _capsule_checks(instance: Node3D) -> void:
	var capsule: CapsuleShape3D = CapsuleShape3D.new()
	capsule.radius = 0.35
	capsule.height = 1.8
	var probe: CharacterBody3D = CharacterBody3D.new()
	probe.collision_layer = 0
	probe.collision_mask = WORLD_LAYER
	var shape: CollisionShape3D = CollisionShape3D.new()
	shape.shape = capsule
	probe.add_child(shape)
	instance.add_child(probe)
	probe.position = Vector3(0, 0.9, -5)
	var hit: KinematicCollision3D = probe.move_and_collide(Vector3(0, 0, 10))
	_expect(hit != null, "Capsule must hit the raised plinth edge")
	_expect(probe.position.z < -3.30 and probe.position.z > -3.36, "Rounded capsule edge stop")
	_result["capsule_edge_stop_z"] = probe.position.z
	probe.position = Vector3(3.5, 0.9, -5)
	hit = probe.move_and_collide(Vector3(0, 0, 10))
	_expect(hit == null, "Capsule must pass beside the circular base")
	_expect(absf(probe.position.z - 5) < TOLERANCE_M, "Bypass ends beyond base")
	_result["capsule_bypass_end_z"] = probe.position.z
	probe.position = Vector3(0, 2, 0)
	hit = probe.move_and_collide(Vector3(0, -2, 0))
	_expect(hit != null, "Deck must support actor-size capsule")
	_expect(absf(probe.position.y - 1.18) < CONTACT_TOLERANCE_M, "Capsule deck support height")
	_result["capsule_supported_centre_y"] = probe.position.y
	probe.queue_free()


## Run bounded resource and physics checks without starting the game or touching live editors.
func _run() -> void:
	if Engine.is_editor_hint():
		# Let editor startup and its filesystem thread finish before save or shutdown.
		await create_timer(EDITOR_STARTUP_SECONDS).timeout
		while EditorInterface.get_resource_filesystem().is_scanning():
			await process_frame  # gdstyle:ignore=quality/await-in-loop

	var arguments: PackedStringArray = OS.get_cmdline_user_args()
	if arguments.has("--normalize"):
		if not Engine.is_editor_hint():
			push_error("Normalize requires headless --editor to preserve scene UIDs")
			quit(1)
			return

		_roundtrip()

	var packed: PackedScene = ResourceLoader.load(
		PREFAB_PATH, "PackedScene", ResourceLoader.CACHE_MODE_IGNORE
	) as PackedScene
	_expect(packed != null, "Prefab dependencies must resolve")
	if packed != null:
		var instance: Node3D = packed.instantiate() as Node3D
		root.add_child(instance)
		_inspect(instance)
		await physics_frame
		await physics_frame
		_physics_checks(instance)
		_capsule_checks(instance)
		instance.queue_free()
		await process_frame

	_result["engine"] = Engine.get_version_info()["string"]
	_result["failures"] = _failures
	_result["ok"] = _failures.is_empty()
	var output: String = DEFAULT_OUTPUT
	var output_index: int = arguments.find("--output")
	if output_index >= 0 and output_index + 1 < arguments.size():
		output = arguments[output_index + 1]

	var file: FileAccess = FileAccess.open(output, FileAccess.WRITE)
	file.store_string(JSON.stringify(_result, "\t") + "\n")
	file.close()
	print(JSON.stringify(_result))
	quit(0 if _failures.is_empty() else 1)
