extends SceneTree

const PREFAB_PATH: String = "res://scenes/prefabs/environment/d01_academic_buildings_01.tscn"
const MODEL_PATH: String = (
	"res://art/models/environment/d01_academic_buildings_01/d01_academic_buildings_01.glb"
)
const DEFAULT_OUTPUT: String = "C:/tmp/ft/assets/d01_academic_buildings_01/prefab-check.json"
const EXPECTED_BOUNDS: AABB = AABB(Vector3(-22.6, 0, -20.765), Vector3(45.2, 21, 41.365))
const TOLERANCE_M: float = 0.001
const WORLD_LAYER: int = 1
const EDITOR_STARTUP_FRAMES: int = 10
const ACTOR_RADIUS_M: float = 0.35
const ACTOR_HEIGHT_M: float = 1.8
const MOTION_TICKS: int = 144

var _failures: Array[String] = []
var _result: Dictionary = {}


## Defer until the headless scene tree can register physics objects.
func _initialize() -> void:
	_run.call_deferred()


## Record a failed assertion and return a nonzero final exit rather than silently continuing.
func _expect(condition: bool, message: String) -> void:
	if not condition:
		_failures.append(message)
		push_error(message)


## Normalize only this owned prefab and prove that a second pack/save is byte-stable.
func _roundtrip() -> void:
	var original: PackedScene = load(PREFAB_PATH) as PackedScene
	_expect(original != null, "Prefab must load before normalization")
	if original == null:
		return

	var instance: Node = original.instantiate()
	var packed: PackedScene = PackedScene.new()
	_expect(packed.pack(instance) == OK, "Prefab pack failed")
	_expect(ResourceSaver.save(packed, PREFAB_PATH) == OK, "Prefab save failed")
	instance.free()
	var first: String = FileAccess.get_sha256(PREFAB_PATH)
	var reloaded: PackedScene = ResourceLoader.load(
		PREFAB_PATH, "PackedScene", ResourceLoader.CACHE_MODE_IGNORE
	) as PackedScene
	instance = reloaded.instantiate()
	packed = PackedScene.new()
	_expect(packed.pack(instance) == OK, "Reloaded prefab pack failed")
	_expect(ResourceSaver.save(packed, PREFAB_PATH) == OK, "Reloaded prefab save failed")
	instance.free()
	_result["save_reload_byte_stable"] = first == FileAccess.get_sha256(PREFAB_PATH)
	_expect(_result["save_reload_byte_stable"], "Second prefab save changed bytes")


## Inspect the linked import, its actual bounds/materials, and authored collision shapes.
func _inspect(instance: Node3D) -> void:
	var model: Node3D = instance.get_node("Visuals/Model") as Node3D
	_expect(model.scene_file_path == MODEL_PATH, "Model lost linked GLB ancestry")
	_expect(model.transform == Transform3D.IDENTITY, "Model transform is not identity")
	var meshes: Array[Node] = model.find_children("*", "MeshInstance3D", true, false)
	_expect(meshes.size() == 1, "Expected one imported mesh")
	var mesh_instance: MeshInstance3D = meshes[0] as MeshInstance3D
	var bounds: AABB = mesh_instance.global_transform * mesh_instance.get_aabb()
	_expect(bounds.position.distance_to(EXPECTED_BOUNDS.position) < TOLERANCE_M, "Bounds min")
	_expect(bounds.size.distance_to(EXPECTED_BOUNDS.size) < TOLERANCE_M, "Bounds size")
	_expect(mesh_instance.mesh.resource_path.begins_with(MODEL_PATH), "Mesh is not imported")
	_expect(mesh_instance.mesh.get_surface_count() == 9, "Expected nine material surfaces")
	var materials: Array[String] = []
	for index: int in range(mesh_instance.mesh.get_surface_count()):
		var material: BaseMaterial3D = (
			mesh_instance.mesh.surface_get_material(index) as BaseMaterial3D
		)
		_expect(material != null, "Missing imported material")
		_expect(material.transparency == BaseMaterial3D.TRANSPARENCY_DISABLED, "Opaque material")
		_expect(material.cull_mode == BaseMaterial3D.CULL_BACK, "Back-culling material")
		materials.append(material.resource_name)

	var body: StaticBody3D = instance.get_node("Collision/Body") as StaticBody3D
	_expect(body.collision_layer == WORLD_LAYER and body.collision_mask == 0, "Static world layers")
	_expect(body.get_child_count() == 3, "Expected main hall and two wing colliders")
	_result["aabb_min"] = [bounds.position.x, bounds.position.y, bounds.position.z]
	_result["aabb_size"] = [bounds.size.x, bounds.size.y, bounds.size.z]
	_result["materials"] = materials
	_result["mesh_count"] = meshes.size()
	_result["collision_shape_count"] = body.get_child_count()
	_result["linked_model_identity"] = model.transform == Transform3D.IDENTITY
	var prefab_uid: int = ResourceLoader.get_resource_uid(PREFAB_PATH)
	var model_uid: int = ResourceLoader.get_resource_uid(MODEL_PATH)
	_expect(prefab_uid != ResourceUID.INVALID_ID, "Prefab UID must be generated by editor save")
	_expect(model_uid != ResourceUID.INVALID_ID, "Model UID must resolve from import sidecar")
	_result["prefab_uid"] = ResourceUID.id_to_text(prefab_uid)
	_result["model_uid"] = ResourceUID.id_to_text(model_uid)


## Query independently specified U footprint corners, solid joints and clear courtyard.
func _physics_checks(instance: Node3D) -> void:
	var space: PhysicsDirectSpaceState3D = instance.get_world_3d().direct_space_state
	var sphere: SphereShape3D = SphereShape3D.new()
	sphere.radius = 0.1
	var cases: Array[Dictionary] = [
		{ "name": "main_hall_solid", "point": Vector3(0, 1, 14), "solid": true },
		{ "name": "closed_arch_solid", "point": Vector3(0, 1, 7.8), "solid": true },
		{ "name": "court_centre_clear", "point": Vector3(0, 1, 0), "solid": false },
		{ "name": "court_mouth_clear", "point": Vector3(0, 1, -20), "solid": false },
		{ "name": "west_wing_solid", "point": Vector3(-17, 1, -10), "solid": true },
		{ "name": "east_wing_solid", "point": Vector3(17, 1, -10), "solid": true },
		{ "name": "west_connection_solid", "point": Vector3(-17, 1, 8), "solid": true },
		{ "name": "east_connection_solid", "point": Vector3(17, 1, 8), "solid": true },
		{ "name": "rear_corner_solid", "point": Vector3(22, 1, 20), "solid": true },
		{ "name": "wing_corner_solid", "point": Vector3(12, 1, -20), "solid": true },
		{ "name": "west_bypass_clear", "point": Vector3(-22.5, 1, 0), "solid": false },
		{ "name": "east_bypass_clear", "point": Vector3(22.5, 1, 0), "solid": false },
		{ "name": "tower_cap_visual_only", "point": Vector3(0, 19, 11.2), "solid": false },
	]
	var observations: Array[Dictionary] = []
	var query: PhysicsShapeQueryParameters3D = PhysicsShapeQueryParameters3D.new()
	query.shape = sphere
	query.collision_mask = WORLD_LAYER
	for test: Dictionary in cases:
		query.transform.origin = test["point"]
		var solid: bool = not space.intersect_shape(query).is_empty()
		_expect(solid == test["solid"], "Shape query failed: " + str(test["name"]))
		observations.append({ "case": test["name"], "solid": solid })

	var ray: PhysicsRayQueryParameters3D = PhysicsRayQueryParameters3D.create(
		Vector3(0, 1, 0), Vector3(0, 1, 14), WORLD_LAYER
	)
	var hit: Dictionary = space.intersect_ray(ray)
	_expect(not hit.is_empty(), "Front ray should hit the closed hall")
	if not hit.is_empty():
		var hit_position: Vector3 = hit["position"]
		_expect(absf(hit_position.z - 7.7) < TOLERANCE_M, "Court facade ray datum must be +7.7 m")
		_result["front_ray_hit"] = [hit_position.x, hit_position.y, hit_position.z]

	_result["physics_shape_queries"] = observations


## Exercise the production movement API against the saved prefab, not a copied movement formula.
func _move_probe(start: Vector3, move: Vector2, mode: ActorMotion.StepMode) -> Vector3:
	var actor: ActorMotion = ActorMotion.new()
	actor.collision_layer = 0
	actor.collision_mask = WORLD_LAYER
	var capsule: CapsuleShape3D = CapsuleShape3D.new()
	capsule.radius = ACTOR_RADIUS_M
	capsule.height = ACTOR_HEIGHT_M
	var collider: CollisionShape3D = CollisionShape3D.new()
	collider.shape = capsule
	collider.position.y = ACTOR_HEIGHT_M / 2.0
	actor.add_child(collider)
	root.add_child(actor)
	actor.position = start
	await physics_frame
	var command: FootCommand = FootCommand.new(1, 0, move, 0.0, false, false)
	var fixed_delta: float = 1.0 / float(Engine.physics_ticks_per_second)
	# Real fixed frames are required: this intentionally serializes the physics probe.
	for tick: int in range(MOTION_TICKS):
		await physics_frame  # gdstyle:ignore=quality/await-in-loop
		_expect(actor.step(command, fixed_delta, mode), "Production motion rejected test intent")

	var end: Vector3 = actor.global_position
	actor.queue_free()
	await physics_frame
	return end


## Prove closed entrance, open court traversal and wing blocking in authority and replay.
func _movement_checks() -> void:
	# Collider-only test ground is not authored visible environment geometry.
	var ground: StaticBody3D = StaticBody3D.new()
	ground.collision_layer = WORLD_LAYER
	ground.collision_mask = 0
	var shape: BoxShape3D = BoxShape3D.new()
	shape.size = Vector3(100, .5, 100)
	var collider: CollisionShape3D = CollisionShape3D.new()
	collider.shape = shape
	collider.position.y = -.25
	ground.add_child(collider)
	root.add_child(ground)
	await physics_frame
	var observations: Array[Dictionary] = []
	# Run modes sequentially so their actor bodies cannot interfere.
	for mode: ActorMotion.StepMode in [ActorMotion.StepMode.AUTHORITY, ActorMotion.StepMode.REPLAY]:
		var entry: Vector3 = await _move_probe(  # gdstyle:ignore=quality/await-in-loop
			Vector3(0, 0, 4), Vector2(0, 1), mode
		)
		_expect(entry.z > 7.30 and entry.z < 7.40, "Actor must stop before closed entrance")
		_expect(absf(entry.y) < .03, "Entry has a flush ground threshold")
		var bypass: Vector3 = await _move_probe(  # gdstyle:ignore=quality/await-in-loop
			Vector3(0, 0, -19), Vector2(0, 1), mode
		)
		_expect(bypass.z > -7.1 and bypass.z < -6.9, "Open court must allow 12 m traversal")
		var wall: Vector3 = await _move_probe(  # gdstyle:ignore=quality/await-in-loop
			Vector3(9, 0, 0), Vector2(1, 0), mode
		)
		_expect(wall.x > 11.40 and wall.x < 11.50, "Wing facade must stop actor")
		observations.append({
			"mode": mode,
			"entry_end": [entry.x, entry.y, entry.z],
			"bypass_end": [bypass.x, bypass.y, bypass.z],
			"wall_end": [wall.x, wall.y, wall.z],
		})

	_expect(observations[0]["entry_end"] == observations[1]["entry_end"], "Entry replay mismatch")
	_expect(
		observations[0]["bypass_end"] == observations[1]["bypass_end"],
		"Bypass replay mismatch",
	)
	_expect(observations[0]["wall_end"] == observations[1]["wall_end"], "Wall replay mismatch")
	_result["production_actor_motion"] = observations
	ground.queue_free()
	await physics_frame


## Run bounded resource and physics checks without starting the game or touching live editors.
func _run() -> void:
	if Engine.is_editor_hint():
		for frame: int in range(EDITOR_STARTUP_FRAMES):
			await process_frame  # gdstyle:ignore=quality/await-in-loop
		while EditorInterface.get_resource_filesystem().is_scanning():
			await process_frame  # gdstyle:ignore=quality/await-in-loop

	var arguments: PackedStringArray = OS.get_cmdline_user_args()
	if arguments.has("--normalize"):
		# Runtime ResourceSaver strips scene/dependency UIDs on this pin.
		_expect(Engine.is_editor_hint(), "UID-preserving normalization requires --editor")
		if Engine.is_editor_hint():
			_roundtrip()

	var packed: PackedScene = ResourceLoader.load(
		PREFAB_PATH, "PackedScene", ResourceLoader.CACHE_MODE_IGNORE
	) as PackedScene
	_expect(packed != null, "Prefab dependencies must resolve")
	if packed != null:
		var instance: Node3D = packed.instantiate() as Node3D
		root.add_child(instance)
		_inspect(instance)
		if not Engine.is_editor_hint():
			await physics_frame
			await physics_frame
			_physics_checks(instance)
			await _movement_checks()
		instance.queue_free()
		await process_frame

	_result["engine"] = Engine.get_version_info()["string"]
	_result["failures"] = _failures
	_result["ok"] = _failures.is_empty()
	var output: String = DEFAULT_OUTPUT
	var output_index: int = arguments.find("--output")
	if output_index >= 0 and output_index + 1 < arguments.size():
		output = arguments[output_index + 1]

	var file: FileAccess = FileAccess.open(output, FileAccess.WRITE)
	file.store_string(JSON.stringify(_result, "\t") + "\n")
	file.close()
	print(JSON.stringify(_result))
	quit(0 if _failures.is_empty() else 1)
